### ISSUE TITLE
Block .SetProperty Bug - cannot get the value from modified text (kodular built-in text tools)

### ISSUE THREAD

**Issue by HeyAveHey** [ysfchn/DynamicComponents-AI2#15] opened 2020-06-21 10:32 UTC
![Inkedblocks(2)_LI](https://user-images.githubusercontent.com/67224301/85222429-2e951580-b3bb-11ea-9b3f-c1bb4c1a9fa5.jpg)
![errorblock](https://user-images.githubusercontent.com/67224301/85222437-4076b880-b3bb-11ea-873a-5fb107d0ca34.PNG)
![Inkedblocks_dziala_LI](https://user-images.githubusercontent.com/67224301/85222447-54bab580-b3bb-11ea-8d97-f81e2ec9aee7.jpg)
![Issue1](https://user-images.githubusercontent.com/67224301/85222482-a3684f80-b3bb-11ea-89a0-c02878ee96f2.PNG)

**Comment by ontstudios** [comment] 2020-06-21 10:57
Can you add a more detailed description of the error?

**Comment by HeyAveHey** [comment] 2020-06-21 11:01
What do you mean by more detailed? Should i describe it better or is there any possibility to make the error more detailed?

**Comment by ontstudios** [comment] 2020-06-21 11:02
Yes, please describe it better. A few images are not enough to see what the problem is.

**Comment by HeyAveHey** [comment] 2020-06-21 11:07
Okay. The problem is the SetProperty block doesn't recognize the text when it is modified with block like "segment text", "split at" etc. As u can see above in the last image, these 2 strings: 1) Witdh!!!! modified by segment function is equal to 2) Width string. But only the string Width works, even those 2 blocks give the same result.

**Comment by HeyAveHey** [comment] 2020-06-21 11:07
So there in practice there are 2 equals values for the Name getter, but only 1 works.

**Comment by HeyAveHey** [comment] 2020-06-21 11:09
And thanks for reply!

**Comment by ontstudios** [comment] 2020-06-21 11:21
Hm, weird, does it also happen if you set the modified string to a variable, and then attach the get {name} block to the `name` socket?

**Comment by HeyAveHey** [comment] 2020-06-21 11:23
[platform-tools_r30.0.1-windows.zip](https://github.com/ysfchn/DynamicComponents-AI2/files/4809353/platform-tools_r30.0.1-windows.zip)

**Comment by HeyAveHey** [comment] 2020-06-21 11:25
![blocks(1)](https://user-images.githubusercontent.com/67224301/85223322-a0bd2880-b3c2-11ea-8baa-ceb15540dde7.png)

Still the same issue.

**Comment by HeyAveHey** [comment] 2020-06-21 11:27
I tried trim, join and more combinations. But it never works.

**Comment by ysfchn** [comment] 2020-06-21 11:30
Can you show the block result by connecting to the companion then using "Do It" feature?

**Comment by ontstudios** [comment] 2020-06-21 11:35
> Can you show the block result by connecting to the companion then using "Do It" feature?

> Issue1

Also, for the OP, what happens if you use this for e.g.
![blocks (58)](https://user-images.githubusercontent.com/63335417/85223499-01009a00-b3c4-11ea-9b4d-8d3f3cf1f532.png)

**Comment by HeyAveHey** [comment] 2020-06-21 11:40
![Uploading issue2.PNG…]()
![issue](https://user-images.githubusercontent.com/67224301/85223642-addb1700-b3c4-11ea-9033-7fbb7cd1f2ec.PNG)

**Comment by HeyAveHey** [comment] 2020-06-21 11:42
But that block without modified string works.

**Comment by ontstudios** [comment] 2020-06-21 11:42
No, press do it on this:
![image](https://user-images.githubusercontent.com/63335417/85223699-16c28f00-b3c5-11ea-9419-fc7e605ce1c5.png)

Right click on the join block > Do it

**Comment by HeyAveHey** [comment] 2020-06-21 11:44
![issue5](https://user-images.githubusercontent.com/67224301/85223741-4b364b00-b3c5-11ea-9bad-16f54ca58bea.PNG)

**Comment by ontstudios** [comment] 2020-06-21 11:47
@ysfchn self-assign this 🤣

**Comment by HeyAveHey** [comment] 2020-06-21 11:50
I'm confused as well. I will bypass the problem with manually created list of parameters strings and will check if any item from my .txt file is equal. If there's a fix please let me know. Thanks for the amazing extension!

**Comment by ysfchn** [comment] 2020-06-21 11:58
Thanks for reporting this, I will check into that and will push a commit if there is a problem with the extension.

**Comment by ysfchn** [comment] 2020-06-23 14:11
@HeyAveHey as I checked, your error is coming from the "component" parameter. It can show the "Invalid property" error when the "component" parameter is not a Component too. **So that was because you were typing a wrong ID to GetComponent block** so it was returning a blank value. 

I changed the GetComponent block to return a blank string when the component couldn't found and added another `if` block for checking if the component parameter is blank or not. 

You can check this commit:
f76c032e2b93558520aab0aaaf040e4b187f55f7

Thanks for testing!

**Closed by ysfchn** 2020-06-23 14:11 UTC
Labels: bug, verify-needed

**Comment by HeyAveHey** [comment] 2020-06-23 20:33
I don't understand it too much. I made it sure to type in a good ID of component. Block doesn't work only if GetProperty gets modified string.

> 
> 
> ![issue5](https://user-images.githubusercontent.com/67224301/85223741-4b364b00-b3c5-11ea-9bad-16f54ca58bea.PNG)

That block doesn't work as well. And I'm sure i did everything OK here. But I managed to bypass the problem. I get my strings for getProperty from manually created list. Only in that case it works. Thanks for answer!

**Comment by HeyAveHey** [comment] 2020-06-23 20:36
Can u test the block in the message above? With segment text function, and without it?

**Comment by ysfchn** [comment] 2020-06-23 20:44
I can't reproduce the issue, so probably something goes wrong from your side, can you try with the latest version too?

**Comment by HeyAveHey** [comment] 2020-06-23 20:55
Ok i GOT this. I used different cellphone and it WORKS! But the issue still persist on the second phone. That's why we had troubles to understand each other ... On Huawei it doesn't work. Xiaomi works perfectly!

**Comment by ysfchn** [comment] 2020-06-23 20:58
Then it is not a problem with my extension then, because extensions are designed to work with App Inventor blocks. If a method doesn't read the value, then it is probably about the App Inventor itself.

**Comment by HeyAveHey** [comment] 2020-06-23 21:02
Thanks again! Sorry, i could check it earlier. What a waste of time for you :/. Good luck in next projects! That's a nice lesson for me, to always check for a simple solution at first.

**Comment by ysfchn** [comment] 2020-06-23 22:41
Oh, no problem of course! Thanks for testing and using my extension! Good luck to you too about your next projects! I would like to see what will you make with the help of my extension! 😊
